### ISSUE TITLE
Package external dependencies

### ISSUE THREAD

**Issue by piotrkochan** [RocketChat/Rocket.Chat.Apps-cli#26]
There is no way to bundle external npm dependencies.

**Comment by kaiiiiiiiii** [comment]
Duplicate of https://github.com/RocketChat/Rocket.Chat.Apps-ts-definition/issues/49

**Comment by graywolf336** [comment]
Closing as a result of duplicate of RocketChat/Rocket.Chat.Apps-ts-definition#49
