### ISSUE TITLE
rc-apps deploy fails "Error: Deployment error: Invalid Version: ^0.9.13"

### ISSUE THREAD

**Issue by wreiske** [RocketChat/Rocket.Chat.Apps-cli#32]
```
rc-apps deploy
packaging your app... packaged!
What is the server's url (include https)?: https://removed/
What is the username?: wreiske
And, what is the password?: ******************************
deploying your app... !
Error: Deployment error: Invalid Version: ^0.9.13
    at Deploy.asyncSubmitData (/usr/local/lib/node_modules/@rocket.chat/apps-cli/lib/commands/deploy.js:75:19)
```

**Comment by kaiiiiiiiii** [comment]
Use version 1.0.0, that’s the first “stable” app framework release which is required for a submit to the App Marketplace. And keep in mind that the ts-definitions moved to the apps-engine package! :)

**Comment by wreiske** [comment]
Just tried setting to 1.0.0 and it worked. Thanks!

**Comment by anikacharjee** [comment]
Error: Deployment error: User does not have the permissions required for this action
    [error-unauthorized]

**Comment by vineetiotina** [comment]
Facing same issue with version 1.17.0
