### ISSUE TITLE
Don't add the @rocket.chat/apps-ts-definition package when generating new apps

### ISSUE THREAD

**Issue by d-gubert** [RocketChat/Rocket.Chat.Apps-cli#35]
When generating an App with the CLI, it still includes in the devDependencies of the `package.json` the https://github.com/RocketChat/Rocket.Chat.Apps-ts-definition package, which is deprecated.

It can also confuse some tools, such as VSCode's "Add missing imports".

**Comment by graywolf336** [comment]
Make sure your CLI version is up to date, as that's not being added anywhere when generating a new app: https://github.com/RocketChat/Rocket.Chat.Apps-cli/blob/master/src/misc/appCreator.ts

**Comment by marceloschmidt** [comment]
The `package.json` has it: 
```
{
    "devDependencies": {
        "@rocket.chat/apps-ts-definition": "^0.9.13",
        "tslint": "^5.10.0",
        "typescript": "^2.9.1"
    }
}
```

**Comment by marceloschmidt** [comment]
Wait, but now that I checked the code, it doesn't... but my repo is up-to-date... weird. Will check

**Comment by marceloschmidt** [comment]
Never mind my previous comments. I didn't realize my `rc-apps` command was not linked to the apps-cli repo.

**Comment by d-gubert** [comment]
It's been solved in the latest releases, closing now
