### ISSUE TITLE
diagnostic.data is not a file

### ISSUE THREAD

**Issue by PierrePaul** [RocketChat/Rocket.Chat.Apps-cli#45]
I'm new to writing extension and I'm quite lost.
When running `rc-apps deploy --url http://localhost:3000 --username admin --password hunter1`, I'm getting the error:

```
packaging your app... done
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: not a file: /home/user1/todo/rocketdb/diagnostic.data
    at /usr/local/lib/node_modules/@rocket.chat/apps-cli/node_modules/yazl/index.js:31:52
    at FSReqWrap.oncomplete (fs.js:153:5)
```

`diagnostic.data` is indeed not a file, it's a directory.
I'm using the `rocketchat/rocket.chat.preview` docker image.
Any help would be appreciated.

**Comment by midse** [comment]
I'm facing the same issue and also using the `rocketchat/rocket.chat.preview` docker image.

**Comment by graywolf336** [comment]
Please open this again if this is still an issue. I'm not sure how we would get around this and prevent it from happening without breaking the current functionality...
