### ISSUE TITLE
Issue Logging in to Rocketchat Server

### ISSUE THREAD

**Issue by benjsicam** [RocketChat/Rocket.Chat.Apps-cli#51]
### Description:

When trying to deploy https://github.com/RocketChat/Apps.Google.Calendar to our RocketChat Server via `rc-apps deploy`, an error occurs saying, "Error: Invalid username and password".

### Steps to reproduce:

1. Clone https://github.com/RocketChat/Apps.Google.Calendar.
2. Open Terminal and `cd` into the clone directory and execute `rc-apps deploy`.
3. Provide the **CORRECT** credentials.

### Expected behavior:

App should be deployed successfully.

### Actual behavior:

An error occurs saying, "Error: Invalid username and password
    at Deploy.asyncSubmitData (~/.nvm/versions/node/v10.16.0/lib/node_modules/@rocket.chat/apps-cli/lib/commands/deploy.js:57:19)"

![rc-apps-deploy-issue](https://user-images.githubusercontent.com/1850054/66178080-ae951700-e696-11e9-887e-36441e308b34.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 1.3.2
- Operating System: Linux
- Deployment Method: Official Docker Image
- Number of Running Instances: 3
- DB Replicaset Oplog: Enabled
- NodeJS Version: 8.11.4
- MongoDB Version: 4.0.12

**Comment by graywolf336** [comment]
Which version of the cli are you using?

**Comment by benjsicam** [comment]
@graywolf336 

```
rc-apps -v
@rocket.chat/apps-cli/1.4.0 linux-x64 node-v10.16.0
```

**Comment by d-gubert** [comment]
We've had problems with accounts that have 2FA enabled before. Do you use 2FA in your setup?

**Comment by benjsicam** [comment]
Hi @d-gubert, we don't use 2FA on our setup.

**Comment by graywolf336** [comment]
<img width="457" alt="Screen Shot 2019-10-17 at 6 58 05 PM" src="https://user-images.githubusercontent.com/850391/67056035-1c6a2580-f110-11e9-925e-9119c0f76293.png">

Try to use your username instead of your email?

**Comment by benjsicam** [comment]
Works! Thanks @graywolf336

**Comment by graywolf336** [comment]
Awesome, thanks for following up!
