### ISSUE TITLE
"Cannot find name 'Buffer'" error occurred when using CLI to create a new app

### ISSUE THREAD

**Issue by lolimay** [RocketChat/Rocket.Chat.Apps-cli#69]
![image](https://user-images.githubusercontent.com/32427260/83027364-9da07800-a062-11ea-8c45-8b56d251988c.png)

PS. It's not a critical error but a typescript "warning".

**Comment by adrianovieira** [comment]
Hi! 
I'm having this same error here.

Did you find any workaround for this issue?

**Comment by lolimay** [comment]
This is not an error but a typescript "warning". You simply ignore it.
