### ISSUE TITLE
Error during deployment: "Invalid filename"

### ISSUE THREAD

**Issue by utnaf** [RocketChat/Rocket.Chat.Apps-cli#91]
Hey there. 
I'm trying to run the `rc-apps deploy --update` command and I get this error

```
Starting App Deployment to Server

   Getting Server Info... ✓
   Packaging the app... ✓
   Uploading App... ✖
 ›   Error:    ⟿  Error: Deployment error: Invalid filename
```

I get I might have a wrong filename but I can't see any way of getting a verbose logging. 
I don't have many files, I just created the app and added a command and that's basically it.

Any suggestion?

This is my rc-apps version `@rocket.chat/apps-cli/1.7.1 darwin-x64 node-v12.16.0`

**Comment by graywolf336** [comment]
@d-gubert here's another one with the exact same issue.

**Comment by d-gubert** [comment]
This problem has been introduced in the new development version of Rocket.Chat (3.8.0) and is not related to the CLI. Please see https://github.com/RocketChat/Rocket.Chat/pull/19411

**Comment by utnaf** [comment]
Ok, thank you for the info
