### ISSUE TITLE
package command creates zip with Javascript files that can't be uploaded

### ISSUE THREAD

**Issue by rowanseymour** [RocketChat/Rocket.Chat.Apps-cli#98]
I'm new to RC app development so hope I'm not doing something silly here, but with https://github.com/RocketChat/Rocket.Chat.Apps-cli/pull/95 I can get `rc-apps package` to work with the default app template, but it creates a `dist/foo_0.0.1.zip` file with my `FooApp.ts` compiled to `FooApp.js`. Which means when I try to upload it into Rocket.Chat I get 

<img width="316" alt="Captura de Pantalla 2020-11-04 a la(s) 15 11 50" src="https://user-images.githubusercontent.com/675558/98163269-96528580-1eb0-11eb-8fc4-2f396481b8f9.png">

Not sure what the expected behavior should be here. Rocket.Chat instance info is:

<img width="520" alt="Captura de Pantalla 2020-11-04 a la(s) 15 21 13" src="https://user-images.githubusercontent.com/675558/98164483-5e4c4200-1eb2-11eb-99d6-6d8b830f3fcd.png">

**Comment by graywolf336** [comment]
@d-gubert maybe the CLI should package up the compiled and the source/typescript 🤔

**Comment by graywolf336** [comment]
To give context here, with the next version of Rocket.Chat it is no longer accepting TypeScript files and only accepting compiled versions of the Apps (Rocket.Chat versions previous would compile at run time each start up). To handle this, the CLI was switched to outputting a compiled package of the App. To get around this, you can do `rc-apps package --no-compile` so I am going to close this issue.
